namespace GFG.Flights.Api.Models;

// Property names align with SQL aliases in AirportRepository.GetCustomerFlightDetailsAsync
public record CustomerFlightDetailDto(
    string? Sex,
    string? PaxName,
    decimal? FltSeqNr,
    string? PaxClass,
    string? Status,
    string? PaxType,
    string? Pnr,
    string? PaxNat,
    string? Boarded,
    string? FfpNum,
    string? FltNr,
    string? AlnCd,
    decimal? LegSeqNr,
    string? ActualDepArpCd,
    string? DepStationName,
    string? ActualArvArpCd,
    string? ArvStationName,
    DateTime? SchDepDt,
    DateTime? SchArvDt,
    DateTime? PubDepDt,
    DateTime? PubArvDt,
    DateTime? ActualDepDt,
    DateTime? ActualArvDt,
    string? CnclCd,
    string? DisruptedFlag,
    string? FfpFlag,
    DateTime? DepDt,
    string? SeatNo,
    string? DocNumber,
    string? MCls,
    string? ManifestTktNr,
    string? Destination,
    DateTime? ManifestDate,
    DateTime? Dob,
    string? PaxDoc,
    string? PaxBoardPoint,
    string? PassengerPhone,
    string? PassengerEmail
);
